### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-multipage-websites#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://aware-queen.surge.sh/students).

**Comment by chrisvfritz** [comment]
Looks great! :shipit: I do notice one tiny inconsistency though: there's [an empty line](https://github.com/KatieMFritz/codelab-multipage-websites/blob/master/students/chris/index.html#L23) before the closing html tag on student pages, but not after the opening tag. Again, just a nitpick. I have to find _something_. :smiley:
